name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  pm2-configuration:
    runs-on: self-hosted
    steps:
      - name: Change to workspace directory
        run: cd $GITHUB_WORKSPACE

      - name: Print final working directory
        run: |
          pwd
          ls

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Print working directory
        run: pwd

      - name: Install PM2
        run: npm install pm2@latest -g

      - name: List PM2 processes
        run: pm2 list

      - name: Start Node.js application with PM2
        run: |
          cd $GITHUB_WORKSPACE  # Go to the workspace directory
          pm2 start index.js
