name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  pm2-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install PM2
        run: npm install pm2@latest -g

      - name: Check PM2 version
        run: pm2 -V

      - name: List PM2 processes
        run: pm2 list

      - name: Start Node.js application with PM2
        run: pm2 start index.js --watch -i max
